language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t $DOCKER_ID/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true $DOCKER_ID/react-test npm run test

after_success:
  - docker build -t $DOCKER_ID/multi-client -f ./client/Dockerfile ./client
  - docker build -t $DOCKER_ID/multi-server -f ./server/Dockerfile ./server
  - docker build -t $DOCKER_ID/multi-worker -f ./worker/Dockerfile ./worker
  - docker build -t $DOCKER_ID/multi-nginx -f ./nginx/Dockerfile ./nginx

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push $DOCKER_ID/multi-client
  - docker push $DOCKER_ID/multi-server
  - docker push $DOCKER_ID/multi-worker
  - docker push $DOCKER_ID/multi-nginx
